[package]
name = "num_convert"
version = "0.3.2"
edition = "2021"
authors = ["Karl Wulfert"]
readme = "README.md"
repository = "https://github.com/pic16f877ccs/num_convert"
license = "GNU General Public License v3.0"
description = "Type converting library, conversions integers by overflow addition, \nsupports generics types."
keywords = ["trait", "generic", "converting", "integers", "overflow-addition"]
categories = ["algorithms"]

[dependencies]
paste = "1.0.8"

[features]
